# Generated by Django 5.2.15 on 2026-06-21 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0005_item_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.CharField(blank=True, default='Uncategorized', max_length=100),
        ),
    ]
