# Generated by Django 5.2.15 on 2026-06-21 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0006_item_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(blank=True, default='None', max_length=100),
        ),
    ]
