# Generated by Django 5.2.15 on 2026-06-21 05:13

from django.db import migrations

def create_none_category(apps, schema_editor):
    Category = apps.get_model("tracking", "Category")
    Category.objects.get_or_create(name="None")

class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0008_category'),
    ]

    operations = [
        migrations.RunPython(create_none_category),
    ]
