# Generated by Django 5.2.15 on 2026-06-21 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0009_create_default_none_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='box_size',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
